"""empty message

Revision ID: 1b8fb0161229
Revises: 76cf79e4e63c
Create Date: 2018-12-28 18:14:36.666784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8fb0161229'
down_revision = '76cf79e4e63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'location')
    # ### end Alembic commands ###
