"""empty message

Revision ID: 4ca86427e729
Revises: e56c3dd23ff8
Create Date: 2018-12-01 21:29:29.362212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca86427e729'
down_revision = 'e56c3dd23ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_token', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_reset_token')
    # ### end Alembic commands ###
