"""empty message

Revision ID: 571805fda94c
Revises: 1b8fb0161229
Create Date: 2018-12-28 18:36:57.320529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571805fda94c'
down_revision = '1b8fb0161229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('details', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'details')
    # ### end Alembic commands ###
