"""Add image_link to  product table

Revision ID: 75f0174add21
Revises: 69e13f562142
Create Date: 2018-11-25 04:04:27.195949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f0174add21'
down_revision = '69e13f562142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_link', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_link')
    # ### end Alembic commands ###
