"""empty message

Revision ID: 76cf79e4e63c
Revises: 650fabaac806
Create Date: 2018-12-25 17:42:58.971846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cf79e4e63c'
down_revision = '650fabaac806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('ad_fee_paid', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'ad_fee_paid')
    # ### end Alembic commands ###
