"""Add category  to  product table

Revision ID: 7f4d0ea353b9
Revises: 75f0174add21
Create Date: 2018-11-25 04:15:21.354781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4d0ea353b9'
down_revision = '75f0174add21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'category')
    # ### end Alembic commands ###
