"""empty message

Revision ID: b0ef6e7cffd7
Revises: 800585ec11b9
Create Date: 2019-01-17 20:26:17.480533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0ef6e7cffd7'
down_revision = '800585ec11b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('code', sa.String(length=255), nullable=True))
    op.drop_column('product', 'details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('details', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('product', 'code')
    # ### end Alembic commands ###
