"""Add Rating Field

Revision ID: c9ad69a07e12
Revises: 4ca86427e729
Create Date: 2018-12-02 15:28:48.962031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ad69a07e12'
down_revision = '4ca86427e729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rating')
    # ### end Alembic commands ###
