"""empty message

Revision ID: e56c3dd23ff8
Revises: c249c5ba2d30
Create Date: 2018-11-28 00:02:33.009052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56c3dd23ff8'
down_revision = 'c249c5ba2d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
