"""empty message

Revision ID: fc0e8fe7f1ca
Revises: 34da2e02ac6d
Create Date: 2018-12-04 18:11:38.808317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc0e8fe7f1ca'
down_revision = '34da2e02ac6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('type', sa.String(length=20), nullable=True))
    op.drop_column('order', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('order', 'type')
    op.drop_column('order', 'seller_id')
    op.drop_column('order', 'buyer_id')
    # ### end Alembic commands ###
